package tokenizer;

public enum TokenType {
	LET, BE, SAY, IF, THEN, REPEAT, TIMES, IS_GREATER_THAN, IS_LESS_THAN, IS_EQUAL,
	NUMBER, STRING, IDENTIFIER, 
	PLUS, MINUS, MULTIPLY, DIVIDE, GREATER, LESS, EQUAL,
	INDENT, DEDENT,NEWLINE, EOF
}
