package tokenizer;

public enum TokenType {
	LET, BE, SAY, IF, THEN, REPEAT, TIMES, IS_GREATER_THAN,
	NUMBER, STRING, IDENTIFIER, 
	PLUS, MINUS, MULTIPLY, DIVIDE, GREATER, LESS, EQUAL,
	NEWLINE, EOF
}
